modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Pocky"

description='''
Advanced solar panel generators for Mekanism.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="[10.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanismgenerators"
    type="required"
    versionRange="[10.7,)"
    ordering="AFTER"
    side="BOTH"
